### PR TITLE
Adding tests and the link feature

### PR DESCRIPTION
**Pull request by Archanium**
The link feature can be seen here: http://tech.quickpay.net/payments/link/

It allows one to generate a link that can then be redirected to. (Thus getting around the pesky issue of order_id's being required to be unique)

### CODE REVIEW

**Comment by sanderha** [comment]
Hey, very cool and it looks like you did a bunch of awesome stuff!

 Just one question though. How come you removed the "type" param from ``` PurchaseRequest::getQuickpayParams() ``` ? It allows for setting either "payment" or "subscription" options for the payment window.

**Comment by Archanium** [comment]
That would be an error on my part! I'll have it fixed this afternoon

**Comment by Archanium** [comment]
Wouldn't the type be called when we're sending the data? And then it won't be needed in the quickpay params?

**Comment by sanderha** [comment]
@Archanium Merged it. Thanks a lot :)

**Pull request merged**
